### PR TITLE
Add Application Name under logo

### PR DESCRIPTION
**Pull request by skng5**
Note: Overrode H1 tag style only for the branding DIV class.

### CODE REVIEW

**Comment by bibliotechy** [comment]
@skng5 Since the logo already says Temple, this should only say "Digital Collections" underneath, not "Temple Digital Collections".

**Comment by skng5** [comment]
We are using the "Application Name" configuration which is "Temple Digital Collections". Are we okay with changing the application name to "Digital Collection"?

**Comment by bibliotechy** [comment]
We could do that or add an additional configuration called `application_short_name` or something like that. Seems like we could logically use both of those across the site.

**Comment by skng5** [comment]
I'll add in the short name

**Comment by bibliotechy** [comment]
:+1:

**Comment by skng5** [comment]
I called it `application_title`. Ready to review and merge.

**Comment by bibliotechy** [comment]
Looking good.

**Pull request merged**
