### PR TITLE
Feature/tulcdm 79 restricted access note

### PR DESCRIPTION
**Pull request by skng5**
Added restricted access note. Full text is shown in link title when user hovers over "restricted access" link in Digital Collection landing page.

### CODE REVIEW

**Comment by kelynch** [comment]
There does not appear to be a title attribute on the restricted collection link with the "access restricted" message in it as we discussed yesterday -- this needs to be implemented for accessibility needs.

**Comment by skng5** [comment]
The original link_to call was lost during branch renaming. It should work now.

**Comment by skng5** [comment]
Also, This requires that you reseed your Rails database before running in order to view a restricted access collection.

**Comment by kelynch** [comment]
Got it -- I did the reseed initially in order to try out the feature so we're good.  Will pull this down and have a look.

**Comment by kelynch** [comment]
Made additional changes to fix the attribute location and its appearance on landing pages.  This looks like it addresses the problem now.

**Comment by kelynch** [comment]
Hrm -- merging develop into the branch (fixing conflict with tul_cdm locale file) suddenly makes the restricted collection just not appear on the index page.  Must drill down before finishing this pull request.

**Comment by kelynch** [comment]
Found the issue -- is_format_based field had not been added to seed.  My guess is this should do it.

**Pull request merged**
