### PR TITLE
Feature/tulcdm 90 inclusive collection facets sidebar

### PR DESCRIPTION
**Pull request by skng5**
Implement facet OR selection (inclusive selection) in sidebar.

### CODE REVIEW

**Comment by kelynch** [comment]
This still purges all other settings from the query including keyword and applied facets if they're applied before the checkboxes are.  As discussed in the dev team meeting, no user-defined parts of the query can be removed from the search before or after these facets are applied.

**Comment by skng5** [comment]
I created separate issues to address this and scrolling (TULCDM 155 and 156 respectively). I will submit a new PR to handle.

**Comment by kelynch** [comment]
I would strongly suggest fixing the bug on this branch and not creating a new feature to deal with a bug introduced in a not-yet-committed feature, given that we are aware of the bug's existence before committing the initial feature.  We really cannot commit a feature that we know is breaking functionality and therefore creating a separate branch to fix it seems unnecessarily risky / messy.

**Comment by skng5** [comment]
Preserves query by using checkbox click events to set or clear faceted OR search.

Please review and if it looks good, merge.

**Comment by skng5** [comment]
Let's hold off on this merge. I want to see if I can use the JS here with the paginated multiselect facets.

**Comment by kelynch** [comment]
:ok:

**Comment by skng5** [comment]
Use paginated facet instead: #54.

**Pull request closed without merging**
