### PR TITLE
Fix Search on Field

### PR DESCRIPTION
**Pull request by skng5**
- Moved default search terms to search_all
- Added more terms for objects where _tesim exists but _sim does not.

### CODE REVIEW

**Comment by kelynch** [comment]
Pulling this down to investigate the issue you described.

**Comment by skng5** [comment]
Fixed bug. Use explicit search term.

**Comment by skng5** [comment]
_Ready to review and merge_

**Comment by skng5** [comment]
Should the solr_name be 'digital_collection_sim' instead of 'digital_collection_tesim'?

**Comment by skng5** [comment]
Digging deeper into the documentation on local_solr_parameters, I found the solr names that the $title_qf and $subject_qf are 'tesim' and the _pf variables are empty.

**Comment by kelynch** [comment]
Is this issue ready to review/possibly merge again?

**Comment by skng5** [comment]
Yes, please review and merge if you think it's good.

**Comment by kelynch** [comment]
OK, will pull down again and review.

**Comment by kelynch** [comment]
:+1:

**Pull request merged**
