### PR TITLE
Override DocumentPresenter field render

### PR DESCRIPTION
**Pull request by bibliotechy**
Update list element text size for consistency

### CODE REVIEW

**Comment by skng5** [comment]
Enclose function arguments in parenthesis here: (https://github.com/tulibraries/tul_cdm/pull/76/files#diff-cb1e07db347c4dafbe5ce4324fba6aceR712)

---

Ref: https://github.com/styleguide/ruby

**Comment by bibliotechy** [comment]
Thanks! I was copying directly from the blacklight code I'm overriding, which apparently is a bad role model. :)
Do you think it is worth setting up https://github.com/bbatsov/rubocop to enforce these things for us?

**Comment by skng5** [comment]
_snicker_

Rubocop sounds like a great idea. I can see how the item I pointed out might be missed.

**Comment by skng5** [comment]
:+1:

**Pull request merged**
