### PR TITLE
Feature/tulcdm 90 faceted basic 'OR' search

### PR DESCRIPTION
**Pull request by skng5**
Added cross-collection search.

Also added BoxSlider to fix unrelated load errors.

### CODE REVIEW

**Comment by kelynch** [comment]
Seeing some odd Solr behavior...reindexing and regenerating seems to do the trick but this one may need additional testing.  

Additionally, the "search by collection" facets not applying even if checked when you hit the primary "search" button is a large enough UX issue that we'll really need to see if we can change that behavior before considering merging into the main branch. :pensive:

**Comment by skng5** [comment]
Associated the inclusive facets with the basic search form. Needs to be checked for functionality and accessibility as we are using form associated elements with the basic search form, since we want to have the facet selector in the side bar which is in a separate div block than the search form.

Still needs pagination so it behaves like the narrowing facet filters.

**Comment by skng5** [comment]
Implements multi-selection facets in both the sidebar widget and in more-facets (paginated) list.

Please review and merge if acceptable.

**Comment by kelynch** [comment]
This looks great!  Merging. :+1:

**Pull request merged**
